In [2]:
#function to convert matrix into reduced row echelon form

def reducedrowechelonform(M):
        for i in range(len(M)):#loop to iterate rows
            for s in range(len(M[0])):
                if i==s:
                    if M[i][s] == 0: #checking if diagonals elements are zero
                        for i2 in range(i+1, len(M)):  #iterating rows below zero diagonal element
                            if M[i2][i2] != 0:
                                for k in range(len(M[0])): #loop to iterate columns
                                    M[i][k],M[i2][k] = M[i2][k],M[i][k] #swapping row with zero diagonal element with other row
                            break
                    else:
                        exit(0)
            for t in range(len(M[0])):
                if i==t:
                    if M[i][t]!=1: #making diagonal elements 1
                        factor=M[i][i]
                        for k3 in range(len(M[0])):
                            M[i][k3]=M[i][k3]/factor
            for j in range(i+1, len(M)):  # making lower triangle zero
                factor = M[j][i]/M[i][i]
                for k2 in range(len(M[0])):
                    M[j][k2] = M[j][k2] - M[i][k2]*factor
            # print pivot
            for z in range(len(M[0])):
                if z==i:
                    if M[z][i]==1:
                        print("PIVOT", i+1,"IN ROW", i+1,",Column",z+1)
            # to make elements above diagonal zero
            for l in range(len(M[0])):
                if i==l:
                    for u in reversed(range(i)):
                        if M[u][l]!=0:
                            for v in range(len(M[0])):
                                subtract=M[i][v]*M[u][l]
                                M[u][l]-=subtract
                    
        return(M)           



In [ ]:
R = int(input("Enter the number of rows:")) 
C = int(input("Enter the number of columns:"))

if R == 0 or C == 0:   
    print("Not a matrix, Rows and Columns should be greater than 1: ")
    
# Initialize matrix 
matrix = [] 
print("Enter the entries rowwise:") 
  
# user input    
for i in range(R):
    print('entering elements of row', i+1)        
    row = []                                      
    for j in range(C):
        element = int(input('enter element: '))   
        row.append(element)                       
    matrix.append(row)

print()   # give an open print space otherwise output looks messy

# For printing the matrix 
for i in range(R): 
    for j in range(C): 
        print(matrix[i][j], end = " ") 
    print()


Enter the number of rows:5
Enter the number of columns:7
Enter the entries rowwise:
entering elements of row 1
enter element: 3
enter element: 11
enter element: 17
enter element: 3
enter element: 90
enter element: 54
enter element: 32
entering elements of row 2
enter element: 1
enter element: 5
enter element: 8
enter element: 91
enter element: 2
enter element: 2
enter element: 25
entering elements of row 3
enter element: 11
enter element: 17
enter element: 28
enter element: 52
enter element: 4
enter element: 2
enter element: 78
entering elements of row 4
enter element: 7
enter element: 9
enter element: 8
enter element: 11
enter element: 23
enter element: 12
enter element: 19
entering elements of row 5
enter element: 89
enter element: 4
enter element: 42
enter element: 23
enter element: 38
enter element: 5
enter element: 43

3 11 17 3 90 54 32 
1 5 8 91 2 2 25 
11 17 28 52 4 2 78 
7 9 8 11 23 12 19 
89 4 42 23 38 5 43 


In [ ]:
reducedrowechelonform(matrix)
print("Reduced row echelon form: ")
for i in range(R): 
    for j in range(C): 
        print(round(matrix[i][j],2), end = " ") 
    print()
#does not work for 3*3=1,2,3,4,5,6,7,8,9  division by zero error

PIVOT 1 IN ROW 1 ,Column 1
PIVOT 2 IN ROW 2 ,Column 2
PIVOT 3 IN ROW 3 ,Column 3
PIVOT 4 IN ROW 4 ,Column 4
PIVOT 5 IN ROW 5 ,Column 5
Reduced row echelon form: 
1.0 0.0 0.0 0.0 0.0 18.0 10.67 
0.0 1.0 0.0 0.0 0.0 -12.0 10.75 
0.0 0.0 1.0 0.0 0.0 -73.23 32.54 
0.0 0.0 0.0 1.0 0.0 -0.28 0.12 
0.0 0.0 0.0 0.0 1.0 0.59 -0.2 


Regression Problem: A programmer is writing a code for a video game. The price of the game y is based on the following equation: y=c0+c1x1+c2x2+c3x3+c4x4+c5x5+c6x6. Where c0,c1,c2...c6 are linear parameters. x1,x2,...,x6 are factors such as lines of code, numbers of hours it took to make the program, cost of the software licences bought to make the game, number of stages, least the number of bugs more the price. x6 depend on the junior programmer's stipend that the programmer have hired. 


In [ ]:
import numpy as np
array=np.random.randint(90,size=(4,6))
print(array)
reducedrowechelonform(array)
print()
print("Linear Regression Solution: ")
print(array)

[[77 65 42 41  5 24]
 [34 59 48 77 63 85]
 [48 77 86 52 81 56]
 [43 55 34 85 21 83]]
PIVOT 1 IN ROW 1 ,Column 1
PIVOT 2 IN ROW 2 ,Column 2
PIVOT 3 IN ROW 3 ,Column 3
PIVOT 4 IN ROW 4 ,Column 4

Linear Regression Solution: 
[[ 1  0  0  0  0  0]
 [ 0  1  0  0  1  1]
 [ 0  0  1  0  0  0]
 [ 0  0  0  1 -1  0]]


Incosistency- model breaks

Acknowledgment-

1. Guided by Akash Gupta, PGDM-2021
2. Machine learning class notes, Rakesh Nigam
3. Discussed with- Sahana, Vamsi, Navin, Palak